# A redirect rule with all the supported properties
[[redirects]]
    from = "https://mentored-sprints.netlify.app/"
    to = "https://mentored-sprints.netlify.app/handbook"
    # The default HTTP status code is 301, but you can define a different one.
    status = 301
    force = true